# Generated by Django 3.2.13 on 2023-10-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(default='movies/poster/not.jpg', upload_to='movies/poster'),
        ),
    ]
